{% set name = "pymapd" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 997327efa40e4c6c0998e0c94daf097ac0527cef6e11c775955ea9a2ef56a025

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vvv"

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
    - numpy >=1.16
    - pyarrow >=0.10
    - packaging >=19.0
  run:
    - python >=3
    - setuptools
    - {{ pin_compatible('numpy') }}
    - pyarrow >=0.10,<0.14
    - pandas >=0.24
    - six
    - sqlalchemy >=1.3
    - thrift 0.11.*
    - packaging >=19.0

test:
  imports:
    - pymapd
    - omnisci
    - omnisci.serialized_result_set
    - omnisci.mapd
    - omnisci.completion_hints
    - omnisci.common

about:
  home: http://github.com/omnisci/pymapd
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'A python DB API 2 compatible client for mapd.'
  description: |
    A python DB API 2 compatible client for mapd.
  doc_url: https://pymapd.readthedocs.io
  dev_url: https://github.com/omnisci/pymapd

extra:
  recipe-maintainers:
    - TomAugspurger
    - andrewseidl
    - randyzwitch
    - xhochy
    - xmnlab
